[build]
start = 'yarn build'
publish = "public
  [build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.preBuild]
    start = 'yarn serve'
    wait-on = 'http://localhost:9000'
    wait-on-timeout = '30' # seconds
    record = true
  [plugins.inputs]
    record = true