[build]
start = 'yarn build'
publish = "public

[[plugins]]
    package = "netlify-plugin-cypress"

    [plugins.inputs.preBuild]
        start = 'yarn serve'
        wait-on = 'http://localhost:9000'
        wait-on-timeout = '30' # seconds
        record = true

    [plugins.inputs]
        record = true