import { createGlobalStyle } from "styled-components"
import styledNormalize from "styled-normalize"

const Font = {
    size: 16,
    family: "Poppins",
}

const Colors = {
    sesame: `#202020`,
    plum: `#4F1C48`,
    ocean: `#304A81`,
    neon: `#D6E307`,
    eggshell: `#D8D8D8`,
}

// Font sizes generated by:
// https://type-scale.com/
const GlobalStyle = createGlobalStyle`    
    ${styledNormalize}

    html {
        font: ${Font.size}px ${Font.family}, sans-serif;        
    }
    body {                
        color: ${props =>
            props.location === "/" ? Colors.eggshell : Colors.sesame};
        background: ${Colors.sesame};
        line-height: 1.65;
    }

    h1, h2, h3, h4, h5, dt {
        font-style: italic;
        line-height: 1.15;
    }
    p, footer, figcaption {
        font-weight: 300;
    }    
    h1, .h1 { 
        font-size: 3.052rem; 
        line-height: 3.125rem; 
    }
    h2, .h2 { font-size: 2.441rem; }
    h3, .h3 { font-size: 1.952rem; }
    h4, .h4 { font-size: 1.563rem; }
    h5, .h5, dt, .lead { font-size: 1.05rem; }
    p, .body { font-size: 1rem; }        
    footer, figcaption, .small { font-size: 0.75rem; }    

    a { color: ${props =>
        props.location === "/" ? Colors.neon : Colors.sesame}}
    b { font-weight: 500}

    dt { margin-top: 1em; }
    dd { 
        margin-left: 0; 
        &:before {
            content: "• ";
        }
    } 
`

export { GlobalStyle, Colors, Font }
