# name: Cypress tests
# on: [push]
# jobs:
#   cypress-run:
#     name: Cypress run
#     runs-on: ubuntu-16.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           record: true
#           start: yarn build && yarn serve
#         env:
#           # pass the Dashboard record key as an environment variable
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           # pass GitHub token to allow accurately detecting a build vs a re-run build
#           GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}

name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cypress run
        uses: cypress-io/github-action@v1
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}      
          CYPRESS_baseUrl: 'https://deploy-preview-${{ github.event.number }--snailbites.netlify.app'
        with:
          wait-on: 'https://deploy-preview-${{ github.event.number }}--snailbites.netlify.app'
          wait-on-timeout: 90
